### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by seeM** [apg-dev/roam-theme-bear#1]
Could you simplify installation using the Stylus browser extension?

**Comment by seeM** [comment]
It looks like with Stylus you also only need to specify properties that you're overriding, so it's a lot easier to work with! For example, see https://github.com/theianjones/roam-research-themes.

**Comment by apg-dev** [comment]
Yes, you could definitely simply using Stylus. I was taking a "no-plugin" approach with this. If you want to use Stylus, I suggest checking out this theme: 

https://raw.githubusercontent.com/vandermerwed/Roam-Research-Dark/master/roam-research-dark.user.css

I may consider creating some Stylus themes as well.

Thank you for the feedback.

**Comment by seeM** [comment]
I see! Good to know. And thank you for the theme 😄 Please feel free to close this if you'd like.
